[package]
name = "m3u8-flash-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
m3u8-flash-core ={ path = "../core" }
clap = "4.5.27"
log = "0.4.25"
env_logger = "0.11.6"

[[bin]]
name = "m3u8-flash"
path = "src/main.rs"